version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: taskflow_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: taskflow_neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  neo4j_data:
